import {
  timestamp,
  uuid,
  varchar,
  pgTable,
  integer,
  boolean,
} from "drizzle-orm/pg-core";

export const orders = pgTable("okataxis_orders", {
  id: uuid("id").defaultRandom().notNull().primaryKey(),
  category: varchar("category").notNull(),
  price: varchar("price").notNull(),
  car: varchar("car").notNull(),
  distance: varchar("distance"),
  stop_1: varchar("stop_1"),
  stop_2: varchar("stop_2"),
  stop_3: varchar("stop_3"),
  pickup_date: timestamp("pickup_date").notNull(),
  pickup_time: varchar("pickup_time").notNull(),
  return_date: timestamp("return_date"),
  return_time: varchar("return_time"),
  is_return: boolean("is_return"),
  pickup_location: varchar("pickup_location").notNull(),
  dropoff_location: varchar("dropoff_location"),
  passengers: integer("passengers").notNull(),
  kids: integer("kids").notNull(),
  bags: integer("bags").notNull(),
  name: varchar("name").notNull(),
  email: varchar("email").notNull(),
  phone: varchar("phone").notNull(),
  flight: varchar("flight"),
  payment_id: varchar("payment_id"),
  payment_method: varchar("payment_method"),
  duration: integer("duration"),
  flight_track: boolean("flight_track"),
  meet_greet: boolean("meet_greet"),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
  created_at: timestamp("created_at").defaultNow().notNull(),
});
